version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.3.1
  node: circleci/node@5.0.2
jobs:
  generate-config:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: .circleci/generated
      - run:
          name: Generate config
          command: node .circleci/generated/index.js
      - continuation/continue:
          configuration_path: ./basic_workflow.yml
workflows:
  dynamic-workflow:
    jobs:
      - generate-config